language: cpp

git:
    depth: 10

compiler:
    - gcc
    - clang

os:
    - osx
    - linux

before_install:
    - if [ $TRAVIS_OS_NAME == linux ]; then 
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && 
      sudo apt-add-repository ppa:sonkun/sfml-development -y && 
      sudo apt-get update -qq;
      fi
    - if [ $TRAVIS_OS_NAME == osx ]; then 
      brew update && 
      brew install sfml;
      fi

install:
    - if [ $TRAVIS_OS_NAME == linux ]; then 
      sudo apt-get install g++-4.8 && 
      sudo apt-get install libsfml-dev;
      fi

script:
    - touch -rbuild/dummy config* aclocal* Makefile* && cd build && ../configure && make
