language: cpp

compiler:
    - gcc
    - clang

os: linux

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-add-repository ppa:sonkun/sfml-development -y
    - sudo apt-get update -qq

install:
    - sudo apt-get install g++-4.8
    - sudo apt-get install libsfml-dev

script:
    - touch -rbuild/dummy config* aclocal* Makefile* && cd build && ../configure && make
